"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/
"""

import os
import dj_database_url
from pathlib import Path
import sys
import psycopg2

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'q7T#dX4zPLg!9vEr1MsK@R8nWhFJc$yAxeZT^2oLB6mCNQb0uGjV*pYIdEUsMw3%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Set to False in production!

# Security Fixes
# Security settings
if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_SSL_HOST = None
else:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_HOST = 'cs3240-s25-a29-eea118da5a2d.herokuapp.com'

ALLOWED_HOSTS = ['cs3240-s25-a29-eea118da5a2d.herokuapp.com', 'localhost', '127.0.0.1']

SOCIALACCOUNT_LOGIN_ON_GET = True

TIME_ZONE = 'America/New_York'
USE_TZ = True
# Application definition
SITE_ID = 2

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.sites",
    'django.contrib.sitemaps',
    'django.contrib.redirects',
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    'movies.apps.MoviesConfig',
    'storages',  # For AWS S3
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Required for static files in local dev
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'movies.middleware.AdminAppSeparationMiddleware',  # Custom middleware to separate admin and app users
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default auth
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth auth
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"}
    }
}

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'movies/templates'),
            os.path.join(BASE_DIR, 'movies/templates/admin'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'movies.context_processors.user_type',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
if 'test' in sys.argv or 'pytest' in sys.argv:
    # Special flag to force SQLite for CI/CD environments
    force_sqlite = os.environ.get('DJANGO_TEST_DB') == 'sqlite'
    
    # Check if we're in a CI/CD environment
    in_ci = any([
        'CI' in os.environ,
        'GITHUB_ACTIONS' in os.environ,
        'TRAVIS' in os.environ,
        'JENKINS_URL' in os.environ,
        'GITLAB_CI' in os.environ,
    ]) or force_sqlite
    
    if in_ci or force_sqlite:
        # Use SQLite for CI/CD tests - fastest and no permission issues
        print("Using SQLite in-memory database for tests")
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': ':memory:',
                'TEST': {
                    'NAME': ':memory:'
                }
            }
        }
        
        # In CI environment, tell Django not to try to set up a test database
        # or run migrations (avoids permission issues and speed up tests)
        class DisableMigrations:
            def __contains__(self, item):
                return True

            def __getitem__(self, item):
                return None

        # Replace migrations with None to skip them
        MIGRATION_MODULES = DisableMigrations()
        
    else:
        # Use PostgreSQL but with setup to avoid creating a new database
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.environ.get('DB_NAME', 'd70e10jgj8460l'),
                'USER': os.environ.get('DB_USER', 'u1sldn8pilujgc'),
                'PASSWORD': os.environ.get('DB_PASSWORD', ''),
                'HOST': os.environ.get('DB_HOST', 'c5p86clmevrg5s.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com'),
                'PORT': os.environ.get('DB_PORT', '5432'),
                'TEST': {
                    'NAME': os.environ.get('DB_NAME', 'd70e10jgj8460l'),
                }
            }
        }
        # Turn off database creation by Django for tests
        DATABASE_ROUTERS = ['movies.test_settings.NoCreateTestDatabaseRouter']
else:
    # Use PostgreSQL for normal operation
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.environ.get('DB_NAME', 'd70e10jgj8460l'),
            'USER': os.environ.get('DB_USER', 'u1sldn8pilujgc'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'c5p86clmevrg5s.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }

# Set DATABASE_URL environment variable to disable SSL in development environment
if 'HEROKU' in os.environ or 'DATABASE_URL' in os.environ:
    # Configure database connection pooling for Heroku
    DATABASES['default']['CONN_MAX_AGE'] = 500  # Keep connections open for longer
    DATABASES['default']['OPTIONS'] = {
        'connect_timeout': 10,  # Shorter timeouts for faster recovery
        'keepalives': 1,         # Enable keepalives
        'keepalives_idle': 60,   # After 60 seconds, send keepalive
        'keepalives_interval': 10, # Send every 10 seconds
        'keepalives_count': 5,    # 5 attempts before failing
    }
    
    # Additional connection settings for Heroku's connection pool behavior
    DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'
    DATABASES['default']['ATOMIC_REQUESTS'] = True  # All requests in single transaction
    
    # Verify settings based on DATABASE_URL if provided
    if 'DATABASE_URL' in os.environ:
        db_from_env = dj_database_url.config(conn_max_age=600, ssl_require=True)
        DATABASES['default'].update(db_from_env)

# Uncomment this for running locally with SQLite
# if "test" in sys.argv:
#     DATABASES["default"] = {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
#     }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/New_York'
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

### STATIC & MEDIA FILES CONFIGURATION ###

# AWS S3 CONFIGURATION
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = 'cs3240-s25-a29'
AWS_S3_REGION_NAME = 'us-east-2' 

AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",  # Cache files for a day
}

AWS_STATIC_LOCATION = "static"
AWS_MEDIA_LOCATION = "media"

# Set URLs for static and media files
STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_STATIC_LOCATION}/"
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_MEDIA_LOCATION}/"

# Set storage backends
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {"location": AWS_MEDIA_LOCATION},  # Store media in /media/
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
        "OPTIONS": {"location": AWS_STATIC_LOCATION},  # Store static files in /static/
    },
}

# DEVELOPMENT: If running locally, serve static files with Whitenoise
if DEBUG:
    STATIC_URL = "/static/"
    # STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
    STORAGES["staticfiles"] = {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    }   

# Directories for local static files (for development)
STATICFILES_DIRS = [
    BASE_DIR / "movies/static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Authentication settings
LOGIN_DIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Test runner settings for database compatibility
if 'test' in sys.argv or 'pytest' in sys.argv:
    TEST_RUNNER = 'movies.test_settings.DatabaseAwareTestRunner'
