# Generated by Django 5.1.5 on 2025-04-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0022_fix_supply_demand_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
