# Generated by Django 5.1.5 on 2025-04-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0023_auto_20250414_0807"),
    ]

    operations = []
